//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HusInfo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public Classification()
        {
            this.Offer = new HashSet<Offer>();
            this.Picture = new HashSet<Picture>();
        }
    
        public int id { get; set; }
        public string problem { get; set; }
        public string type { get; set; }
        public Nullable<int> reportId { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
