//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HusInfo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseInfoContext : DbContext
    {
        public HouseInfoContext()
            : base("name=dmaa0912JesperHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classification { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
