//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HusInfo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Picture = new HashSet<Picture>();
            this.Report = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public Nullable<double> basementAreal { get; set; }
        public Nullable<double> bruttoprice { get; set; }
        public Nullable<int> buildingYear { get; set; }
        public Nullable<double> cashPrice { get; set; }
        public string city { get; set; }
        public Nullable<double> distToSchool { get; set; }
        public Nullable<double> distToShopping { get; set; }
        public string energyMark { get; set; }
        public Nullable<int> floorLevels { get; set; }
        public Nullable<double> garageKvm { get; set; }
        public Nullable<double> groundAreal { get; set; }
        public Nullable<double> kvmPrice { get; set; }
        public Nullable<double> livingAreal { get; set; }
        public Nullable<double> nettoPrice { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> toilets { get; set; }
        public string webLink { get; set; }
        public Nullable<int> zipCode { get; set; }
        public Nullable<int> loginId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<Report> Report { get; set; }
    }
}
