<?xml version="1.0" encoding="utf-8"?><Database Name="dmaa0912JesperH" Class="houseDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=balder.ucn.dk;Initial Catalog=dmaa0912JesperH;Persist Security Info=True;User ID=dmaa0912JesperH" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dmaa0912JesperHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Classification" Member="Classifications">
    <Type Name="Classification">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="problem" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="problemPicture" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="reportId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Classification_Offer" Member="Offers" ThisKey="id" OtherKey="classificationId" Type="Offer" />
      <Association Name="Report_Classification" Member="Report" ThisKey="reportId" OtherKey="id" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.House" Member="Houses">
    <Type Name="House">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="basementAreal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bruttoprice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="buildingYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cashPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="distToSchool" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="distToShopping" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="energyMark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="floorLevels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="garageKvm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="groundAreal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="kvmPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="livingAreal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nettoPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rooms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toilets" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="webLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zipCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loginId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="House_Report" Member="Reports" ThisKey="id" OtherKey="houseId" Type="Report" />
      <Association Name="House_HousePic" Member="HousePics" ThisKey="id" OtherKey="houseId" Type="HousePic" />
      <Association Name="Login_House" Member="Login" ThisKey="loginId" OtherKey="id" Type="Login" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="personType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Login_House" Member="Houses" ThisKey="id" OtherKey="loginId" Type="House" />
      <Association Name="Login_Offer" Member="Offers" ThisKey="id" OtherKey="loginId" Type="Offer" />
    </Type>
  </Table>
  <Table Name="dbo.Offer" Member="Offers">
    <Type Name="Offer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loginId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="classificationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Classification_Offer" Member="Classification" ThisKey="classificationId" OtherKey="id" Type="Classification" IsForeignKey="true" />
      <Association Name="Login_Offer" Member="Login" ThisKey="loginId" OtherKey="id" Type="Login" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="houseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Report_Classification" Member="Classifications" ThisKey="id" OtherKey="reportId" Type="Classification" />
      <Association Name="House_Report" Member="House" ThisKey="houseId" OtherKey="id" Type="House" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HousePic" Member="HousePics">
    <Type Name="HousePic">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="picture" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="houseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="House_HousePic" Member="House" ThisKey="houseId" OtherKey="id" Type="House" IsForeignKey="true" />
    </Type>
  </Table>
</Database>